FROM php:cli
MAINTAINER Guillaume BARRANCO <guillaume.barranco@free.fr>

ARG DOCKER_UID
ARG DOCKER_GID

COPY ./root/update_uid_gid.sh /root/update_uid_gid.sh

RUN /root/update_uid_gid.sh

RUN apt-get update && apt-get install -y wget git

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html

RUN wget https://get.symfony.com/cli/installer -O - | bash && mv /root/.symfony/bin/symfony /usr/local/bin/symfony && symfony new --full eclipse-phase
